name = "SimUtils"
uuid = "042f21a8-4046-4c2b-b9ed-b6e14110b343"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
